default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: sample_message_app_development

test:
  <<: *default
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV["DB_PASSWORD"] %>
  database: sample_message_app_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
