# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.3.0'

gem 'bcrypt', '~> 3.1.7'
gem 'pg', '~> 1.5'
gem 'puma', '>= 5.0'
gem 'rack-cors', '~> 2.0'
gem 'rails', '~> 7.1.0'

group :development, :test do
  gem 'debug', platforms: %i[mri windows]
  gem 'rubocop', require: false
  gem 'rubocop-minitest', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
end
